### ISSUE TITLE
Does not connect on linux

### ISSUE THREAD

**Issue by anmej** [plule/vox-uristi#28]
Hi.
I wanted to try vox-uristi. I have a fresh DF, dfhack, and vox-uristi that I compiled on Ubuntu 20. It opens fine, but can't seem to communicate with DF with a message "Connection refused (os error 111)"

**Comment by plule** [comment]
Which version of df/dfhack are you using? Can you try rebooting? maybe the port was not free and it's listening on another

**Comment by anmej** [comment]
I have to current Steam Dwarf Fortress (50.09) and dfhack (50.09-r2). I tried rebooting, and I'm getting the same error, but also os error 32. Here's the terminal output:

2023-07-29T18:28:12.803195Z  WARN winit::platform_impl::platform::x11: Unsupported locale "en_IL". Restoring default locale "C".    
2023-07-29T18:28:12.838310Z  INFO winit::platform_impl::platform::x11::window: Guessed window scale factor: 1.25    
2023-07-29T18:28:12.895659Z  INFO dfhack_remote::channel: Connecting to 127.0.0.1:5000    
Warning: failed to close the connection to dfhack-remote: communication failure: Broken pipe (os error 32)
2023-07-29T18:28:17.689022Z  INFO dfhack_remote::channel: Connecting to 127.0.0.1:5000

**Comment by plule** [comment]
Well, I just did a double check with the exact same version of Dwarf Fortress and DFHack, and it works fine. The only notable difference is that I’m testing on an ubuntu 22.04 and not a 20.

Few more checks that you can attempt:
- Double checking that DFHack was correctly loaded in game (icon on the top-left)
- Check if [Armok Vision](https://github.com/RosaryMala/armok-vision/releases/tag/v0.21.0) works. Vox Uristi uses the exact same technology to connect to DF, so this could help finding out if the issue is on DFHack side or on Vox Uristi side

**Comment by anmej** [comment]
I took the extreme step to update my Ubuntu (it was time anyway), so now I'm on version 22.04 as well.
I've compiled vox-uristi again, reinstalled both DF and DFHack, and it still wasn't working, but then I changed the proton version used to open DF in Steam, and now it does connect! Hurray.

**Comment by plule** [comment]
Glad to hear! Let's hope this process will be less painful when a native DF is out
